name: 'Dependabot Alert Export With FilePath'
description: 'Export the Dependabot alerts to CSV'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: true
  repo_name:
    description: 'Repository name'
    required: true  
  csv_path:
    description: 'CSV File path'
    required: true
outputs:
  alerts_count:
    description: Number of vulnerability alerts    
runs:
  using: 'node16'
  main: 'app/index.js'
